#!/bin/sh

nvidia-settings --assign CurrentMetaMode="DP-2: nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }, DP-4: nvidia-auto-select +3840+0 { ForceFullCompositionPipeline = On }"
xrandr --output DP-2 --left-of DP-4

sxhkd &

# Assign workspaces to monitors.
berryc save_monitor 0 0
berryc save_monitor 1 0
berryc save_monitor 2 0
berryc save_monitor 3 0
berryc save_monitor 4 0
berryc save_monitor 5 1
berryc save_monitor 6 1
berryc save_monitor 7 1
berryc save_monitor 8 1
berryc save_monitor 9 1

# Set decoration geometry.
berryc border_width 0
berryc inner_border_width 4
berryc title_height 32
berryc top_gap 52
berryc edge_gap 16 16 16 16

# Set decoration colors.
berryc focus_color 282A36
berryc unfocus_color 282A36
berryc inner_focus_color 556FFF
berryc inner_unfocus_color 414458
berryc text_focus_color ffffff
berryc text_unfocus_color eeeeee

berryc smart_place "true"
berryc draw_text "true"
berryc edge_lock "true"
berryc set_font "Fira Code-8"

$HOME/.config/polybar/launch

$HOME/.fehbg
