#!/bin/sh

source $(dirname $0)/config

(echo " $@"; sleep $NOTIFY_DURATION) \
    | lemonbar \
        -g "$NOTIFY_GEOMETRY" \
        -f "$FONT" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" \
        -u "$LINE_HEIGHT"
