#!/bin/sh

sxhkd &

bspc config border_width 2
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle true

bspc monitor -d I II III IV V VI VII VIII IX X

# Note: Use `xprop | rg WM_CLASS` to get window names.
bspc rule -a Pavucontrol state=floating
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a discord desktop='^10' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^10' state=floating follow=on

$HOME/.config/polybar/launch

$HOME/.fehbg
