#!/bin/sh

nvidia-settings --assign CurrentMetaMode="DP-2: nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }, DP-4: nvidia-auto-select +3840+0 { ForceFullCompositionPipeline = On }"
xrandr --output DP-2 --left-of DP-4

sxhkd &

bspc config border_width 2
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle true

bspc monitor DP-2 -d I II III IV V
bspc monitor DP-4 -d VI VII VIII IX X

# Note: Use `xprop | rg WM_CLASS` to get window names.
bspc rule -a Pavucontrol state=floating
bspc rule -a net-runelite-client-RuneLite state=pseudo_tiled
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a discord desktop='^10' state=pseudo_tiled follow=on
bspc rule -a TelegramDesktop desktop='^10' state=pseudo_tiled follow=on

$HOME/.config/polybar/launch

$HOME/.fehbg
