#!/bin/sh

sxhkd &

bspc config border_width 2
bspc config window_gap 16

bspc config split_ratio 0.52
bspc config borderless_monocle true

bspc monitor -d I II III IV V VI VII VIII IX X

$HOME/.config/polybar/launch

$HOME/.fehbg
