#!/bin/sh

cd $(dirname $0)
source $(dirname $0)/config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %Y-%m-%d %I:%M %p' > "$PANEL_FIFO" &
./notify_mpd -d &

cat "$PANEL_FIFO" \
    | ./panel_bar \
    | lemonbar \
        -g "$PANEL_GEOMETRY" \
        -f "$FONT" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" &

wait
