#!/bin/sh

set -m

VPN_URL=sstp.gravic.com

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi

read -p "Username: " USERNAME

read -s -p "Password: " PASSWORD

echo ""
echo "Connecting to $VPN_URL..."

sstpc --log-stderr --cert-warn --user "$USERNAME" --password "$PASSWORD" $VPN_URL usepeerdns require-mschap-v2 noauth noipdefault defaultroute refuse-eap noccp --log-level 4 &

sleep 1
ip route add 10.0.0.0/16 via 10.0.0.211 dev ppp0

fg
