#!/bin/sh

ln -i -s $(pwd)/Xresources ~/.Xresources

mkdir -p ~/.config/nixpkgs
ln -i -s $(pwd)/config/nixpkgs/config.nix ~/.config/nixpkgs/config.nix
ln -i -s $(pwd)/config/nixpkgs/home.nix ~/.config/nixpkgs/home.nix

mkdir -p ~/.config/alacritty
ln -i -s $(pwd)/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml

mkdir -p ~/.config/bspwm
ln -i -s $(pwd)/config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc

mkdir -p ~/.config/fontconfig/conf.d
ln -i -s $(pwd)/config/fontconfig/conf.d/01-emoji.conf ~/.config/fontconfig/conf.d/01-emoji.conf

mkdir -p ~/.config/polybar
ln -i -s $(pwd)/config/polybar/config ~/.config/polybar/config
ln -i -s $(pwd)/config/polybar/launch ~/.config/polybar/launch
ln -i -s $(pwd)/config/polybar/now_playing ~/.config/polybar/now_playing

mkdir -p ~/.config/sxhkd
ln -i -s $(pwd)/config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc

mkdir -p ~/.colors
ln -i -s $(pwd)/colors/ephemeral ~/.colors/ephemeral
ln -i -s $(pwd)/colors/lovelace ~/.colors/lovelace
ln -i -s $(pwd)/colors/manta ~/.colors/manta
ln -i -s $(pwd)/colors/nord ~/.colors/nord
ln -i -s $(pwd)/colors/s3r0 ~/.colors/s3r0
ln -i -s $(pwd)/colors/skyfall ~/.colors/skyfall

mkdir -p ~/.devenv
ln -i -s $(pwd)/devenv/purescript.nix ~/.devenv/purescript.nix

mkdir -p ~/.scripts
ln -i -s $(pwd)/scripts/google-chrome-dark ~/.scripts/google-chrome-dark
ln -i -s $(pwd)/scripts/gravic_vpn ~/.scripts/gravic_vpn
ln -i -s $(pwd)/scripts/osrs ~/.scripts/osrs
ln -i -s $(pwd)/scripts/screenshot ~/.scripts/screenshot
ln -i -s $(pwd)/scripts/showcolors ~/.scripts/showcolors
ln -i -s $(pwd)/scripts/showfont ~/.scripts/showfont

mkdir -p ~/.stack
ln -i -s $(pwd)/stack/config.yaml ~/.stack/config.yaml
