#!/bin/sh

if [ `uname -s` != "Linux" ]; then
    echo "This doesn't look like Linux: `uname -s`"
    exit 1
fi

DOTS="vimrc xinitrc Xresources zprofile zshrc"

DIR=~/dotfiles/arch
CONFDIR=~/dotfiles/arch/config
COLORSDIR=~/dotfiles/arch/colors
SCRIPTSDIR=~/dotfiles/arch/scripts
NCMPCPPDIR=~/dotfiles/arch/ncmpcpp

DEST_DIR=~/
DEST_CONFDIR=~/.config
DEST_COLORSDIR=~/.colors
DEST_SCRIPTSDIR=~/.scripts
DEST_NCMPCPPDIR=~/.ncmpcpp

echo "Initializing dotfiles:"

cd $DIR

echo "=> creating directories"

if [ ! -d $DEST_DIR ]; then
    mkdir -p $DEST_DIR
fi

if [ ! -d $DEST_CONFDIR ]; then
    mkdir -p $DEST_CONFDIR
fi

if [ ! -d $DEST_COLORSDIR ]; then
    mkdir -p $DEST_COLORSDIR
fi

if [ ! -d $DEST_SCRIPTSDIR ]; then
    mkdir -p $DEST_SCRIPTSDIR
fi

if [ ! -d $DEST_NCMPCPPDIR ]; then
    mkdir -p $DEST_NCMPCPPDIR
fi

echo "=> symlinking dotfiles"

for file in $DOTS; do
    if [ -z $DEST_DIR/.$file ] || [ -d $DEST_DIR/.$file ]; then
        rm -rf $DEST_DIR/.$file
    fi

    ln -sf $DIR/$file $DEST_DIR/.$file
done

echo "=> symlinking configs"

for file in `ls $CONFDIR | xargs`; do
    if [ -z $DEST_CONFDIR/$file ] || [ -d $DEST_CONFDIR/$file ]; then
        rm -rf $DEST_CONFDIR/$file
    fi

    ln -sf $CONFDIR/$file $DEST_CONFDIR/$file
done

echo "=> symlinking colors"

for file in `ls $COLORSDIR | xargs`; do
    if [ -z $DEST_COLORSDIR/$file ] || [ -d $DEST_COLORSDIR/$file ]; then
        rm -rf $DEST_COLORSDIR/$file
    fi

    ln -sf $COLORSDIR/$file $DEST_COLORSDIR/$file
done

echo "=> symlinking scripts"

for file in `ls $SCRIPTSDIR | xargs`; do
    if [ -z $DEST_SCRIPTSDIR/$file ] || [ -d $DEST_SCRIPTSDIR/$file ]; then
        rm -rf $DEST_SCRIPTSDIR/$file
    fi

    ln -sf $SCRIPTSDIR/$file $DEST_SCRIPTSDIR/$file
done

echo "=> symlinking ncmpcpp"

for file in `ls $NCMPCPPDIR | xargs`; do
    if [ -z $DEST_NCMPCPPDIR/$file ] || [ -d $DEST_NCMPCPPDIR/$file ]; then
        rm -rf $DEST_NCMPCPPDIR/$file
    fi

    ln -sf $NCMPCPPDIR/$file $DEST_NCMPCPPDIR/$file
done

echo "=> done"
