#!/bin/sh

if [[ $(pgrep -cx mpd) -eq 0 && $(pgrep -cx mopidy) -eq 0 ]] ; then
    exit 1
fi

err() {
    echo "$1"
    exit 1
}

usage() {
    echo "usage: notify_mpd [option]"
    echo
    echo "Options:"
    echo "  -n, --next      - next track"
    echo "  -p, --prev      - previous track"
    echo "  -t, --toggle    - toggle pause"
    echo "  -d, --daemon    - listen for track changes through mpd frontends"
    echo "  -h, --help      - display this"
    exit
}

notify() {
    $(dirname $0)/notify "$@" &
}

state() {
    mpc | sed -n 's/^.*\[\([^\[].*\)\] .*$/\1/p' | uniq
}

case $1 in
    '-p'|'--prev')
        mpc prev
        icon='[Prev]'
        ;;
    '-n'|'--next')
        mpc next
        icon='[Next]'
        ;;
    '-t'|'--toggle')
        mpc toggle
        if [[ `state` == 'paused' ]] ; then
            icon='[Pause]'
        elif [[ `state` == 'playing' ]] ; then
            icon='[Play]'
        fi
        ;;
    '-d'|'--daemon')
        while true; do
            info=$(mpc current --wait)
            notify $info
        done
        ;;
    ''|'-h'|'--help')
        usage
        ;;
    *)
        err "Unrecognized option \`$1\`, see notify_mpd --help"
esac

notify $icon $(mpc current)
