#!/bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

/home/maxdeviant/.config/bspwm/panel/panel &
