#!/bin/sh

# Kill all running bar instances.
killall -q polybar

# Wait until the processes have finished shutting down.
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch the panel bar.
polybar panel &
