#!/bin/sh

track_info() {
    playerctl --player=spotify,spotifyd metadata --format "{{ title }} - {{ artist }}"
}

if [ "$(playerctl --player=spotify,spotifyd status)" = "Stopped" ]; then
    echo ""
elif [ "$(playerctl --player=spotify,spotifyd status)" = "Paused" ]; then
    track_info
else
    track_info
fi
