#!/bin/sh

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This doesn't look like OS X: $(uname -s)"
    exit 1
fi

DOTS="vimrc"

DIR=~/dotfiles/osx
CONFIG_DIR=~/dotfiles/osx/config
COLORS_DIR=~/dotfiles/osx/colors
SCRIPTS_DIR=~/dotfiles/osx/scripts

DEST_DIR=~/
DEST_CONFIG_DIR=~/.config
DEST_COLORS_DIR=~/.colors
DEST_SCRIPTS_DIR=~/.scripts

echo "Initializing dotfiles:"

cd $DIR || exit

echo "=> creating directories"

if [ ! -d $DEST_DIR ]; then
    mkdir -p $DEST_DIR
fi

if [ ! -d $DEST_CONFIG_DIR ]; then
    mkdir -p $DEST_CONFIG_DIR
fi

if [ ! -d $DEST_COLORS_DIR ]; then
    mkdir -p $DEST_COLORS_DIR
fi

if [ ! -d $DEST_SCRIPTS_DIR ]; then
    mkdir -p $DEST_SCRIPTS_DIR
fi

echo "=> symlinking dotfiles"

for file in $DOTS; do
    if [ -e "$DEST_DIR/.$file" ] || [ -d "$DEST_DIR/.$file" ]; then
        rm -rf "$DEST_DIR/.$file"
    fi

    ln -sf "$DIR/$file $DEST_DIR/.$file"
done

echo "=> symlinking configs"

for file in $(ls $CONFIG_DIR | xargs); do
    if [ -e "$DEST_CONFIG_DIR/$file" ] || [ -d "$DEST_CONFIG_DIR/$file" ]; then
        rm -rf "${$DEST_CONFIG_DIR/$file:?}"
    fi

    ln -sf "$CONFIG_DIR/$file $DEST_CONFIG_DIR/$file"
done

echo "=> symlinking colors"

for file in $(ls $COLORS_DIR | xargs); do
    if [ -e "$DEST_COLORS_DIR/$file" ] || [ -d "$DEST_COLORS_DIR/$file" ]; then
        rm -rf "${$DEST_COLORS_DIR/$file:?}"
    fi

    ln -sf "$COLORS_DIR/$file $DEST_COLORS_DIR/$file"
done

echo "=> symlinking scripts"

for file in $(ls $SCRIPTS_DIR | xargs); do
    if [ -e "$DEST_SCRIPTS_DIR/$file" ] || [ -d "$DEST_SCRIPTS_DIR/$file" ]; then
        rm -rf "${$DEST_SCRIPTS_DIR/$file:?}"
    fi

    ln -sf "$SCRIPTS_DIR/$file $DEST_SCRIPTS_DIR/$file"
done

echo "=> done"
